import {
  LayoutDashboard,
  ShoppingCart,
  TrendingUp,
  Wallet,
  Landmark,
  Boxes,
  Users,
  Truck,
  Receipt,
  Building,
  ClipboardList,
  BookOpen,
  Scale,
  FileBarChart,
  Repeat,
  PieChart,
  PersonStandingIcon,
  WalletCardsIcon,
  DollarSignIcon,
} from "lucide-react";

export const navigationItems = [
  { label: "الرئيسية", path: "/dashboard", icon: LayoutDashboard },
  {
    label: " المبيعات و المشتريات",
    path: "/dashboard/sales",
    icon: TrendingUp,
  },
  { label: "العملاء/الموردين", path: "/dashboard/partners", icon: Users },
  { label: "الخزينة", path: "/dashboard/treasury", icon: Wallet },
  { label: "البنك", path: "/dashboard/bank", icon: Landmark },
  { label: "المخازن", path: "/dashboard/inventory", icon: Boxes },
  { label: "المصاريف", path: "/dashboard/expenses", icon: Receipt },
  { label: " الأجور -المرتبات", path: "/dashboard/assets", icon: Building },
  {
    label: " ميزان المراجعة",
    path: "/dashboard/reconciliation",
    icon: ClipboardList,
  },
  { label: "قيود اليومية", path: "/dashboard/journal-entries", icon: BookOpen },
  {
    label: "ميزان بعد التسوية",
    path: "/dashboard/adjusted-trial-balance",
    icon: Scale,
  },
  {
    label: "  الدخل",
    path: "/dashboard/income",
    icon: Repeat,
  },
  {
    label: "تقارير المركز المالي",
    path: "/dashboard/financial-position",
    icon: PieChart,
  },
  { label: "التقارير", path: "/dashboard/reports", icon: FileBarChart },
  {
    label: "الصلاحيات",
    path: "/dashboard/permissions",
    icon: PersonStandingIcon,
  },
];
